{% set name = "autogluon.multimodal" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/autogluon/autogluon/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 96075e9bfce79420fe78a5566a1ba82f9a80598e955f4a4fc490f5561ede70bd
  # Use the latest commit temporarily
  url: https://github.com/autogluon/autogluon/archive/e6458bdbbaa22908457a199f1095b80edc3b85f9.tar.gz
  sha256: 39e542cfc5f7d5ba767dbb20fa462d9a7d535115011b3cd2e98dd70175090722

build:
  # noarch: python
  skip: true  # [win or py>=311]
  skip: true  # [linux and cuda_compiler_version not in ("None", "11.2")]
  script: {{ PYTHON }} -m pip install ./multimodal -vv
  number: 6
  script_env:
   - RELEASE=1

requirements:
  build:
    - {{ compiler('cuda') }}                 # [linux and cuda_compiler_version != "None"]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy  >=1.21,<1.27                    # [build_platform != target_platform]
  host:
    - python # >=3.8,<3.11
    - pip
  run:
    - python # >=3.8,<3.11
    - numpy >=1.21,<1.27
    - scipy >=1.5.4,<1.12
    - pandas >=1.4.1,<1.6
    - scikit-learn >=1.0,<1.3
    - pillow >=9.3,<9.6
    - tqdm >=4.38,<5
    - boto3 >=1.10,<2
    - requests >=2.21,<3
    - jsonschema <4.18  # jsonschema @ 4.17.3
    - seqeval <1.3.0  # seqeval @ 1.2.2
    - evaluate <0.4.0  # evaluate @ 0.3.0
    - accelerate >=0.9,<0.17  # accelerate @ 0.16
    - timm <0.7.0  # timm @ 0.6.12
    - pytorch >=1.9,<1.14  # pytorch @ 1.13.1
    - torchvision <0.15.0  # torchvision @ 0.14.1
    # - torchtext <0.15  # [not arm64]  torchtext @ 0.14.1
    - fairscale >=0.4.5,<0.4.14  # [not win]  fairscale @ 0.4.13
    - scikit-image >=0.19.1,<0.20.0  # scikit-image @ 0.19.3
    # - smart_open >=5.2.1,<5.3.0  # smart_open @ 6.3.0
    - pytorch-lightning >=1.8.0,<1.10.0  # pytorch-lightning @ 1.9.0
    - text-unidecode <=1.4  # text-unidecode @ 1.3.0
    - torchmetrics >=0.8.0,<0.9.0  # torchmetrics @ 0.11.1
    - transformers >=4.23.0,<4.27.0  # transformers @ 4.26.0
    - nptyping >=1.4.4,<2.5.0  # nptyping @ 2.4.1
    - omegaconf >=2.1.1,<2.3.0  # omegaconf @ 2.3.0
    - sentencepiece >=0.1.95,<0.2.0  # sentencepiece @ 0.1.97
    - pytorch-metric-learning >=1.3.0,<2.0  # pytorch-metric-learning @ 2.0.0
    - nlpaug >=1.1.10,<1.2.0  # nlpaug @ 1.1.11
    - nltk >=3.4.5,<4.0.0  # nltk @ 3.8.1
    - openmim >0.1.5,<0.4.0 # openmim @ 0.3.5
    - defusedxml >=0.7.1,<0.7.2  # defusedxml @ 0.7.1
    # - albumentations >=1.1.0,<=1.2.0  # albumentations @ 1.3.0
    - jinja2 >=3.0.3,<3.2
    - tensorboard >=2.9.1,<2.12
    - pytesseract >=0.3.9,<0.3.11
    - autogluon.core =={{ version }}
    - autogluon.features =={{ version }}
    - autogluon.common =={{ version }}

test:
  imports:
    - autogluon.multimodal
  commands:
    - python -c "from autogluon.multimodal import __version__ as v; assert v == '{{ version }}', f'{v} != {{ version }}'"
  requires:
    - pip
    - pytorch =*=cuda*  # [linux and cuda_compiler_version != "None"]

about:
  home: https://pypi.org/project/autogluon.multimodal
  summary: AutoML for Image, Text, and Tabular Data
  description: |
    AutoGluon automates machine learning tasks enabling you to easily achieve strong 
    predictive performance in your applications. With just a few lines of code, you 
    can train and deploy high-accuracy machine learning and deep learning models on 
    image, text, time series, and tabular data.  
  dev_url: https://github.com/autogluon/autogluon/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - Innixma
